### ISSUE TITLE
How to store new users with this lib

### ISSUE THREAD

**Issue by slidenerd** [TrejGun/mongo-bot-storage#1]
I understand that statements such as session.userData.name = session.message.user.name will store the name of the person directly inside mongodb, I would like to store and delete users when they are added or removed inside contactRelationUpdate or conversationUpdate events. How can I trigger this lib to store and delete data during those events. Thanks for your answers in advance

**Comment by TrejGun** [comment]
@slidenerd
sorry, completely missed your message.
i believe bot events are not related to any storage type, you probably should ask there for help
